"""recipe complexity added

Revision ID: 0a52f4f8a7a4
Revises: 5d810980a63e
Create Date: 2023-11-08 13:17:51.924790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a52f4f8a7a4'
down_revision: Union[str, None] = '5d810980a63e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
