"""recipe complexity added

Revision ID: 5d810980a63e
Revises: 8c21e8a5af19
Create Date: 2023-11-08 11:06:31.510372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d810980a63e'
down_revision: Union[str, None] = '8c21e8a5af19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('RECIPES', sa.Column('complexity', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('RECIPES', 'complexity')
    # ### end Alembic commands ###
